version: "2.19.1"

services:
  blockly-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: blockly-db
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: timothydatonsthanhson
      MONGO_INITDB_DATABASE: blockly
    networks:
      - blockly-network
    restart: always

  blockly-be:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: blockly-be
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mongodb://root:timothydatonsthanhson@blockly-db:27018/blockly?authSource=admin
      PORT: 8000
      ENCRYPT_KEY: datons2024emforem
      ADMIN_KEY: 4D63458A41E6FA6CEF24BE6F57E27
      JWT_SECRET: datons2024bandforband
    depends_on:
      - blockly-db
    networks:
      - blockly-network
    restart: always

  blockly-be-clone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: blockly-be-clone
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: mongodb://root:timothydatonsthanhson@blockly-db:27018/blockly-clone?authSource=admin
      PORT: 8001
      ENCRYPT_KEY: datons2024emforem
      ADMIN_KEY: 4D63458A41E6FA6CEF24BE6F57E27
      JWT_SECRET: datons2024emforem
    depends_on:
      - blockly-db
    networks:
      - blockly-network
    restart: always

volumes:
  mongo-data:

networks:
  blockly-network:
