version: '3.8'

services:
  blockly-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: blockly-db
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

  blockly-be:
    build: .
    container_name: blockly-be
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mongodb://blockly-db:27018/blockly
      PORT: 8000
    depends_on:
      - blockly-db

volumes:
  mongo-data:
